apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: ns-admin-role
    namespace: homework
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin-rb
  namespace: homework
roleRef:
  kind: Role
  name: ns-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cd
  name: cd-token
  namespace: homework
type: kubernetes.io/service-account-token

