apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.nsadmin.name }}
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.nsadmin.name }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindings.nsadmin.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.roles.nsadmin.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.nsadmin.name }}
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.secrets.nsadmin.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.secrets.nsadmin.metadata.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/service-account-token

