apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "homechart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port.num }}
      name: {{ .Values.service.port.name }}
      targetPort: {{ .Values.service.targetPort }}

